version: "3"

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: 'single-node'
    networks:
      - elasticnet
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    restart: always
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: 'http://elastic:9200'
    networks:
      - elasticnet
    volumes:
      - kibana_data:/usr/share/kibana
networks:
  elasticnet:

volumes:
  elasticsearch_data:
  kibana_data:
